name 'rbenv_resources'
maintainer 'David Pell'
maintainer_email 'davidcpell@gmail.com'
license 'all_rights'
description 'Provides resources for installing/configuring rbenv'
long_description 'Provides resources for installing/configuring rbenv'
version '0.6.0'

supports 'ubuntu', '>= 14.04'
supports 'centos', '= 7.2'
