name 'ws_ruby'
maintainer 'David Pell'
maintainer_email 'davidcpell@gmail.com'
license 'all_rights'
description 'Provides resources for installing/configuring rbenv'
long_description 'Provides resources for installing/configuring rbenv'
version '0.1.0'
